Fix some problems with Docker container (#243)
* update v1.1.1 (#233)

* Update addon.xml

V.1.1.0

* Docker build schlägt fehl wegen PEP-668 - Marking Python base environments as “externally managed” (#232)

* Update addon.xml

V.1.1.0

* do not delete files in case provided locally

* Add Python virtual environment

PEP-668 marks the Python base environment as "externally managed" and breaks the Docker build.
This adds a Python virtual environment to the image.

Signed-off-by: clocken <66382986+clocken@users.noreply.github.com>

---------

Signed-off-by: clocken <66382986+clocken@users.noreply.github.com>
Co-authored-by: codingPF <j-doo@gmx.de>

* typo

* issue with epoch 2200

* update version

---------

Signed-off-by: clocken <66382986+clocken@users.noreply.github.com>
Co-authored-by: clocken <66382986+clocken@users.noreply.github.com>

* make docker/95_mediathekview_db executable

This fixes the
  /package/admin/s6-overlay-3.2.0.2/etc/s6-rc/scripts/cont-init: line 20: /etc/cont-init.d/95_mediathekview_db: Permission denied
error message when starting the container.

* explicitly install version 9.1.0 of mysql-connector-python package

Starting with version 9.2.0 the cursor.execute() method does not support
the "multi" parameter any more, leading to error message
  TypeError: MySQLCursor.execute() got an unexpected keyword argument 'multi'

By pinning the mysql-connector-python version to 9.1.0 the updater works,
for now.

---------

Signed-off-by: clocken <66382986+clocken@users.noreply.github.com>
Co-authored-by: codingPF <j-doo@gmx.de>
Co-authored-by: clocken <66382986+clocken@users.noreply.github.com>