explicitly install version 9.1.0 of mysql-connector-python package
Starting with version 9.2.0 the cursor.execute() method does not support
the "multi" parameter any more, leading to error message
  TypeError: MySQLCursor.execute() got an unexpected keyword argument 'multi'

By pinning the mysql-connector-python version to 9.1.0 the updater works,
for now.